name: Deploy to Firebase Hosting

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: dist   # 👈 tutto avviene in dist/

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Write Firebase service account key
        run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > $GITHUB_WORKSPACE/dist/firebase-key.json

      - name: Deploy to Firebase
        run: |
          firebase deploy \
            --only hosting \
            --non-interactive \
            --project agenda-carmenmauro \
            --config firebase.json
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $GITHUB_WORKSPACE/dist/firebase-key.json